Setapp/Models/PerformanceTestsResults.cs
using Setapp.Business;

namespace Setapp.Models
{
    public class PerformanceTestsResults
    {
        public readonly TimeComparision FillingData;
        public readonly TimeComparision RetrievingDataByIndexColumn;
        public readonly TimeComparision RetrievingDataByUnindexColumn;
        public readonly TimeComparision RetrievingMultipleObjectsByUnindexColumn;
        public readonly TimeComparision RetrievingCountByUnindexedValue;

        public PerformanceTestsResults(
            TimeComparision fillingData,
            TimeComparision retrievingDataByIndexColumn,
            TimeComparision retrievingDataByUnindexColumn,
            TimeComparision retrievingMultipleObjectsByUnindexColumn,
            TimeComparision retrievingCountByUnindexedValue)
        {
            FillingData = fillingData;
            RetrievingDataByIndexColumn = retrievingDataByIndexColumn;
            RetrievingDataByUnindexColumn = retrievingDataByUnindexColumn;
            RetrievingMultipleObjectsByUnindexColumn = retrievingMultipleObjectsByUnindexColumn;
            RetrievingCountByUnindexedValue = retrievingCountByUnindexedValue;
        }
    }
}

Setapp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Setapp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Setapp/Controllers/PerformanceTestsController.cs
using System.Web.Mvc;
using Setapp.Business;
using Setapp.Models;

namespace Setapp.Controllers
{
    public class PerformanceTestsController : Controller
    {
        public ActionResult Index()
        {
            var performanceTests = new PerformanceTests();
            PerformanceTestsResults testsResults = performanceTests.RunTests();

            return View(testsResults);
        }
    }
}

Setapp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Performance tests</title>
</head>
<body>
    <h1>Performance tests</h1>
    <p>To run performance tests click @Html.ActionLink("HERE", "Index", "PerformanceTests")</p>
    <p>It can take about 20 minutes to see the results</p>
</body>
</html>

Setapp/Views/PerformanceTests/Index.cshtml
@model Setapp.Models.PerformanceTestsResults

<h1>Tests results</h1>

<div>
    <h2>Filling data</h2>
    <ul>
        <li>Entity Framwork avarage time: @Model.FillingData.EntityFrameworkExecutionTime ms</li>
        <li>Custom table avarage time: @Model.FillingData.CustomTableExecutionTime ms</li>
    </ul>
    
    <h2>Retriving data by indexed column</h2>
    <ul>
        <li>Entity Framwork avarage time: @Model.RetrievingDataByIndexColumn.EntityFrameworkExecutionTime ms</li>
        <li>Custom table avarage time: @Model.RetrievingDataByIndexColumn.CustomTableExecutionTime ms</li>
    </ul>
    
    <h2>Retriving data by unindexed column</h2>
    <ul>
        <li>Entity Framwork avarage time: @Model.RetrievingDataByUnindexColumn.EntityFrameworkExecutionTime ms</li>
        <li>Custom table avarage time: @Model.RetrievingDataByUnindexColumn.CustomTableExecutionTime ms</li>
    </ul>

    <h2>Retriving multiple objects by unindexed column</h2>
    <ul>
        <li>Entity Framwork avarage time: @Model.RetrievingMultipleObjectsByUnindexColumn.EntityFrameworkExecutionTime ms</li>
        <li>Custom table avarage time: @Model.RetrievingMultipleObjectsByUnindexColumn.CustomTableExecutionTime ms</li>
    </ul>

    <h2>Retriving count by unindexed column</h2>
    <ul>
        <li>Entity Framwork avarage time: @Model.RetrievingCountByUnindexedValue.EntityFrameworkExecutionTime ms</li>
        <li>Custom table avarage time: @Model.RetrievingCountByUnindexedValue.CustomTableExecutionTime ms</li>
    </ul>
</div>